services:
  postgres:
    image: postgres-postgis
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_17_data:/var/lib/postgresql/data

volumes:
  postgres_17_data: